## cachematrix.R
## by Avery Johnson

## These functions are designed to cache the inverse of a matrix
## so that it can be retrieved multiple timeswithout having to calculate the
## inverse more than once.

## This function takes a matrix, x, and returns a list of functions that
## can be used to retrieve information about x. These functions are:
##  - set(): can be used to set the matrix
##  - get(): retrieves the matrix
##  - setInverse(): sets the inverse to the passed in argument
##  - getInverse(): returns the inverse
makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y) {
        x <<- y
        inv <<- NULL
    }
    get <- function() x;
    
    setInverse <- function(newInverse) {
        inv <<- newInverse
    }
    getInverse <- function() inv
    list(set = set, get = get, setInverse = setInverse,
         getInverse = getInverse)
}


## This function takes a list, x, of functions generated by the makeCacheMatrix
## function and returns the inverse of the matrix referenced by those functions
cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    inv <- x$getInverse()
    if (!is.null(inv)){
        ## If the inverse is cached, it is returned 
        ## without calling solve.
        print("retrieving cached")
        return(inv)
    }
    ##  If the inverse is not stored, it is calculated and returned.
    data <- x$get()
    inv <- solve(data)
    x$setInverse(inv)
    return(inv)
}
